package jp.sakuramochi.kaisatsupatch.core

import java.io.File
import java.nio.charset.Charset
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

/**
 * KaisatsuNetworkData の路線・駅データから OuDia 1.02 形式のテンプレートを生成する。
 * 時刻欄はすべて空欄で、駅順・種別・ダイヤ構造だけを出力する。
 */
object OuDiaExporter {

    private val SJIS = try { Charset.forName("Shift_JIS") } catch (_: Exception) { Charsets.UTF_8 }

    /** デフォルトの列車種別リスト */
    private val DEFAULT_TYPES = listOf(
        "普通"  to "00000000",
        "急行"  to "00FF0000",
        "特急"  to "00FF6600",
        "新幹線" to "000000FF"
    )

    /**
     * 単一路線のテンプレートを生成して [outputDir]/[filename] に書き出す。
     * @param line   路線データ
     * @param trainTypes  種別リスト（空なら DEFAULT_TYPES を使用）
     * @param diaNames    ダイヤ名リスト（空なら ["平日","土曜","休日"] を使用）
     * @param trainCountPerDia 各ダイヤ・方向あたりの列車スロット数
     * @return 書き出したファイルの絶対パス
     */
    fun exportLine(
        line: KaisatsuNetworkData.LineData,
        outputDir: File,
        filename: String = "${line.lineID}.oud",
        trainTypes: List<Pair<String, String>> = DEFAULT_TYPES,
        diaNames: List<String> = listOf("平日", "土曜", "休日"),
        trainCountPerDia: Int = 3
    ): File {
        outputDir.mkdirs()
        val file = File(outputDir, filename)
        val sb = buildTemplate(
            routeName = line.lineName,
            stations  = line.stationOrder.toList(),
            types     = trainTypes,
            diaNames  = diaNames,
            trainCount = trainCountPerDia
        )
        file.writeText(sb, SJIS)
        return file
    }

    /**
     * 全グローバル駅を使ったテンプレートを生成する。
     * 駅順は globalStations のキーをアルファベット順にソートしたもの。
     */
    fun exportAll(
        data: KaisatsuNetworkData,
        outputDir: File,
        filename: String = "template.oud",
        diaNames: List<String> = listOf("平日", "土曜", "休日"),
        trainCountPerDia: Int = 3
    ): File {
        outputDir.mkdirs()
        val file = File(outputDir, filename)
        val sb = buildTemplate(
            routeName = "全駅テンプレート",
            stations  = data.globalStations.keys.sorted(),
            types     = DEFAULT_TYPES,
            diaNames  = diaNames,
            trainCount = trainCountPerDia
        )
        file.writeText(sb, SJIS)
        return file
    }

    // ── 内部実装 ──────────────────────────────────────────────────────

    private fun buildTemplate(
        routeName: String,
        stations: List<String>,
        types: List<Pair<String, String>>,
        diaNames: List<String>,
        trainCount: Int
    ): String {
        val ts = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))
        val sb = StringBuilder()

        sb.appendLine("FileType=OuDia.1.02")
        sb.appendLine("Rosen.")

        // ── 駅リスト ──────────────────────────────────────
        sb.appendLine("EkiList.")
        stations.forEach { st ->
            sb.appendLine("Eki.")
            sb.appendLine("Ekimei=$st")
            sb.appendLine("EkiJikokukeisokutyouhouhou=Jikokukeisoku_Hatsu")
            sb.appendLine("DiagramDgrRowProperty=DgrRow_Eki")
            sb.appendLine(".")
        }
        sb.appendLine("EkiListEnd")

        // ── 列車種別 ──────────────────────────────────────
        types.forEach { (name, color) ->
            sb.appendLine("Ressyasyubetsu.")
            sb.appendLine("Syubetsumei=$name")
            sb.appendLine("JikokuhyouMojiColor=00$color")
            sb.appendLine("JikokuhyouFontIndex=0")
            sb.appendLine("DiagramSenColor=00$color")
            sb.appendLine("DiagramSenStyle=SenStyle_Jissen")
            sb.appendLine("DiagramSenIsBold=0")
            sb.appendLine(".")
        }

        // ── ダイヤ（複数） ──────────────────────────────────
        val emptySemicolons = ";".repeat(stations.size)  // 駅数分のセミコロン（空欄）

        diaNames.forEach { diaName ->
            sb.appendLine("Dia.")
            sb.appendLine("DiaName=$diaName")

            listOf("Kudari" to "下り", "Nobori" to "上り").forEach { (tag, _) ->
                sb.appendLine("$tag.")
                repeat(trainCount) { idx ->
                    sb.appendLine("Ressya.")
                    sb.appendLine("Ressyasyubetuindex=0")
                    sb.appendLine("Ressyabangou=")
                    sb.appendLine("Ressyamei=")
                    sb.appendLine("EkiJikoku=$emptySemicolons")
                    sb.appendLine(".")
                }
                sb.appendLine("${tag}End")
            }

            sb.appendLine(".")
        }

        sb.appendLine(".")   // Rosen 終端

        // ファイル末尾に生成情報コメント（OuDia は '#' コメントを無視する）
        sb.appendLine("# Generated by RTM Kaisatsu Patch at $ts")
        sb.appendLine("# Route: $routeName (${stations.size} stations)")
        sb.appendLine("# Edit departure times (HHMM format) after semicolons in EkiJikoku fields")

        return sb.toString()
    }
}
